var a = parseInt(Math.random()*(15-1)+1);
document.write(" <br />" );
document.write(" <br />" );
switch (a) {
             case 1 : document.write(" Это было число  1" );
                        break;
             case 2 : document.write(" Это было число  2" );
                        break;
             case 3 : document.write(" Это было число  3" );
                        break;
             case 4 : document.write(" Это было число 4" );
                        break;
             case 5 : document.write(" Это было число 5" );
                        break;
             case 6 : document.write(" Это было число 6" );
                        break;
             case 7 : document.write(" Это было число 7" );
                        break;
             case 8 : document.write(" Это было число 8" );
                        break;
             case 9 : document.write(" Это было число 9" );
                        break;
             case 10 : document.write(" Это было число 10" );
                        break;
             case 11 : document.write(" Это было число 11" );
                        break;
             case 12 : document.write(" Это было число 12" );
                        break;
             case 13 : document.write(" Это было число 13" );
                        break;
             case 14 : document.write(" Это было число 14" );
                        break;
             case 15 : document.write(" Это было число 15" );
                        break;             
}document.write(" <br />" );
/* end of file */